all: setup lint build

setup:
	pip install --user setuptools wheel pylint pytest

setup-travis:
	pip install setuptools wheel pylint pytest tox-travis

run:
	python3 -m bindilla

build:
	python3 setup.py bdist_wheel
.PHONY: build

build-docker:
	docker build --tag stencila/bindilla .

run-docker:
	docker run -p 8888:8888 -it stencila/bindilla

install:
	pip install --user .

lint:
	pylint bindilla

test:
	tox

cover:
	tox -e cover

docs:
	echo "$$(sed '/<!-- Autogenerated docs, do not edit below here! -->/q' README.md)" "\n\n$$(pydocmd simple bindilla.host.Host++ bindilla.host_http_server++)" > README.md
	sed -i -e 's/h3/h5/g' -e 's/h2/h4/g' -e 's/h1/h3/g' README.md

clean:
	rm -rf bindilla/*.pyc build dist bindilla.egg-info
